### ISSUE TITLE
pypi.org Documentation link still old

### ISSUE THREAD

**Issue by derMart** [sylikc/pyexiftool#27]
https://pypi.org/project/PyExifTool/ -> Project Links -> Documentation still links to http://smarnach.github.io/pyexiftool/ instead of http://sylikc.github.io/pyexiftool/

cheers
Martin

**Comment by sylikc** [comment]
Thanks for the issue submission.  I had to change setup.py to reflect the current repo URL

resolved with a PyPI release and commit eaa480734840840693e5cbe41d434ff0f602bb0d
