### ISSUE TITLE
Documentation in https://sylikc.github.io/pyexiftool/ is not up to date

### ISSUE THREAD

**Issue by derMart** [sylikc/pyexiftool#28]
There are a lot of missing functions, such as `set_tags` etc.
EDIT: also code still links to `git clone git://github.com/smarnach/pyexiftool.git`

**Comment by sylikc** [comment]
@derMart  yeah... the documentation is certainly not up to date... I've certainly fallen behind documenting all the things I merged way back when.

Are you familiar with documenting with sphinx?  I'll take in pull requests for documentation updates :)

Right now all work is going into the python 3.x refactor branch.  Is there a particular method you would like to see documentation for, and I'd go merge just that? :D

**Comment by yellowtailfan** [comment]
A couple of specific issues with the documentation:
1. The `common_args` parameter in `exiftool.ExifTool()` is missing from the website (it is mentioned in the docstring though)
2. The docstring for `exiftool.ExifTool()` describes a parameter `print_conversion` that is not implemented

**Comment by sylikc** [comment]
Yeaaah... I need to go rebuild docs with at least the latest docstring.  The current pyexiftool reincarnation is certainly much different than when smarnach left off with it

**Comment by sylikc** [comment]
I'm updating the documentation for v0.5.0 ... should have something ready and published soon hopefully.

Expanding the documentation significantly from the single-page that it used to be before

**Comment by sylikc** [comment]
@derMart @yellowtailfan @jangop Documentation is updated!  Please review and leave comments....

It's really my first time ever writing so much RST... I tried to make it as pretty as possible 😅

Let me know if the layout and design makes sense.  I decided to leave the autodoc stuff in, because I don't know how to add references to certain things otherwise.

https://sylikc.github.io/pyexiftool/

**Comment by yellowtailfan** [comment]
Much improved! 👏

**Comment by derMart** [comment]
Wow, big improvement! Many thanks

**Comment by jangop** [comment]
I'll go over it soon.

**Comment by sylikc** [comment]
ok, I'm closing this issue... let me know if there's anything else you'd like to see in documentation!
