### ISSUE TITLE
any idea on how to strip all metadata?

### ISSUE THREAD

**Issue by sathio** [sylikc/pyexiftool#33]
how would I do the equivalent of: `exiftool -all= path_to_file`

I can't find it and on the doc it says that the `execute` function should not be used by developers.

thanks

**Comment by sathio** [comment]
seems that it likes it this way

`self.exiftool.execute(f'-all=\n{filename}'.encode('utf-8'))`

**Comment by sylikc** [comment]
I need to change that comment.  I think ```execute()``` should be used in the cases where nothing is expected to return.  In the new Python3 branch https://github.com/sylikc/pyexiftool/tree/v0.5.x-py3-refactor, ```execute_json()``` will just return ```None``` and you could use it just the same.

But you shouldn't use any ```\n``` in your code to ```execute()```

The v0.4.x Python2 way required encoding each parameter manually.... 
```self.exiftool.execute(b'-all=', filename.encode('utf-8'))```
