### ISSUE TITLE
Can output formats be specified using exiftool.ExifToolHelper()?  

### ISSUE THREAD

**Issue by abetomas** [sylikc/pyexiftool#43]
Can output formats be specified using exiftool.ExifToolHelper()?  I tried the formatting date for CreateDate and it did not work.  
- the tagname was returned together with a groupname. 
- I wanted to get the actual value of the TAG using get_tags() but the returned values included sourcefile and groupname:tagname. 
- I previously used the older version of pyexiftool >> xx.get_tag('CreateDate', FileName) << will return only value of CreateDate without sourcefile and tagnames.  

 >>> 
 >>> import exiftool
 >>> 
 >>> with exiftool.ExifToolHelper() as et:
 ...     md=et.get_tags('./misc/20190105_153439.mp4','CreateDate',['-r','-s','-d','%Y-%m-%d'])
 ...     print(md)
 ... 
 [{'SourceFile': './misc/20190105_153439.mp4', 'QuickTime:CreateDate': '2019:01:21 22:08:12'}]
 >>> 

**********
Note: using exiftool.ExifTool() applies the date format specified in the common_args list 
and tagname does not contain groupname.  
**********
 >>> 
 >>> import exiftool
 >>> 
 >>> with exiftool.ExifTool(common_args= ['-r','-s','-d','%Y-%m-%d','-CreateDate']) as et:
 ...     md = et.execute_json("./misc/20190105_153439.mp4")
 ... 
 >>> print(md)
 [{'SourceFile': './misc/20190105_153439.mp4', 'CreateDate': '2019-01-21'}]

Thanks again for your help.

**Comment by sylikc** [comment]
I just pushed out a new release.  ```ExifToolHelper.get_tags()``` isn't the same as the original ```get_tag()``` functionality.  I had currently left that functionality in ```ExifToolAlpha``` because it can cause some inadvertent behavior.

In v0.4, try doing something like ExifTool.get_tag("*.mp4", "CreateDate") and wonder which is related to which file to get a sense of the problem...

So the functionality you're looking for is ```ExifToolAlpha.get_tag()``` .  Try that

**Comment by abetomas** [comment]
Thanks.. The exiftool.ExifTool() works out for me for now.
