### ISSUE TITLE
Documentation of .encoding - UTF-8 vs utf-8

### ISSUE THREAD

**Issue by nitmws** [sylikc/pyexiftool#58]
The documentation of _propertyexiftool.ExifTool.encoding_ tells:

_Default to `UTF-8` if nothing is returned ..._

But the code of the @encoding.setter is:

`ENCODING_UTF8: str = "utf-8"`
... and ...
`self._encoding = new_encoding or (locale.getpreferredencoding(do_setlocale=False) or ENCODING_UTF8)
`

Therefore the documentation should tell:

_Defaults to `utf-8` if nothing is returned ..._

... else debugging people like me may be wondering why the self._encoding value is not 'UTF-8'.

**Comment by sylikc** [comment]
fair point.  I'll rebuild the documentation later, but I fixed it in the docstring.  thanks for the input
