### ISSUE TITLE
Exiftool location

### ISSUE THREAD

**Issue by tester0077** [sylikc/pyexiftool#62]
What assumptions are made regarding the location of the Exiftool library/executable?
Is there a way specify a specific path or executable?
For Windows>
For Linux?

I have a packaged app - Gramps AIO  https://gramps-project.org/blog/ - and would like to be able to use the Python interface, but under windows there seems to be no way.
I am inexperienced enough to not be able to figure that out from the Python source of this interface
**Edit:**
At present, Gramps marks the plugin unavailable if it cannot find the exiftool executable while it is parsing the "import exiftool" statement.
Edit 2:
For Windows, Exiftool.exe is on the PATH

**Comment by sylikc** [comment]
The `executable` property is used to specify the executable, or in the constructor.  https://sylikc.github.io/pyexiftool/reference/1-exiftool.html#exiftool.ExifTool.executable

As per the documentation, the default executable is `exiftool.exe` on windows, and `exiftool` on linux.  As long as it's found in the PATH, it will be detected by pyexiftool

**Comment by tester0077** [comment]
Understood, but as far as I know, either version (Phil Harvey's or Oliver Betz's) needs a number of supporting files and data. 
I have raised a question on the Gramps forum whether there is an equivalent place as part of its AIO package to which I could (manually if necessary). copy the required files.
While I am waiting for clarification, (and I don't know if this is the proper place to ask,) I do worry as to what algorithm that executable would use to look for support files: relative to the EXE's location or would it also use the PATH.

**Comment by emyoulation** [comment]
@tester0077 
The [version options ](https://gramps-project.org/wiki/index.php/Gramps_5.1_Wiki_Manual_-_Command_Line#Version_options) for the Gramps executable will list paths for your installation. The text-based list includes Python and the OS environment variables.

**Comment by tester0077** [comment]
That data is for the linux version :-)
On my Win machine I have:
_PYTHONPATH:
    C:\Program Files\GrampsAIO64-5.1.5\gramps
    C:\Program Files\GrampsAIO64-5.1.5
    C:\Program Files\GrampsAIO64-5.1.5\lib
    C:\Program Files\GrampsAIO64-5.1.5\lib/python36.zip
    C:\Program Files\GrampsAIO64-5.1.5\lib\python3.6
    C:\Program Files\GrampsAIO64-5.1.5\lib\python3.6\lib-dynload
    C:/building/msys64/mingw64
_
Which is all well & good, but
a) there are too many possibilities for a brute force approach which would try all possible options/combinations
b) Exiftool's algorithm may well differ and look for other places
c) would I try all this with the Windows or Linux version?

**Comment by emyoulation** [comment]
hmmm... looks like my (Windows) copy from the CLI window didn't overwrite the (linux) clip from the Wiki.

Are you looking for: 
```
C:\Program Files\GrampsAIO64-5.1.5\lib\girepository-1.0\GExiv2-0.10.typelib
C:\Program Files\GrampsAIO64-5.1.5\libgexiv2-2.dll
C:\Program Files\GrampsAIO64-5.1.5\libexiv2.dll
```

**Comment by tester0077** [comment]
AFAIK, it is not so much a matter of finding the app's location, but how to make the plug-in and its host code within the Gramps AIO package aware of and able to use it.
I just don't know enough about what is going on inside the AIO code. Had tried to follow a suggestion and code for another gramplet which 'imports' some needed code, but had no luck with that either.

**Comment by sylikc** [comment]
@tester0077 I'm unable to help you on this thread as I don't have familiarity with the Gramps project.  Please ask on their forums or file an issue on their bug tracker.  You can even link to this issue, if it is related to something PyExifTool is doing.

Otherwise, I'm closing the issue for now.  Thanks for everyone else who commented with suggestions!
