### ISSUE TITLE
why XMP tag not add to IPTC  Please donnot ignore?

### ISSUE THREAD

**Issue by faridelya** [sylikc/pyexiftool#72]
As I am using this code and the tag name is from XMP  but i have mentioned IPTC 

```
from exiftool import ExifTool
with ExifTool() as et:
    print(et.execute(*["-IPTC:Subject=hi"] + ["skyblue.png"]))

```
Thanks please write your precious answer

**Comment by sylikc** [comment]
@faridelya have you tried this on the command line without using python?  this would better be asked as an upstream question on the exiftool forums.  Issues here are for the python interface to the exiftool utility.
