### ISSUE TITLE
How to set arguments for EXIFTool?

### ISSUE THREAD

**Issue by llitkr** [sylikc/pyexiftool#77]
I'm trying to read lot of metadatas from video files. Some of them are very big size.

When I try to read metadata of big file, the message appeared like this 
"SourceFile": "2023-02-05/20230923_124112(AX700).MP4",
                "ExifTool:ExifToolVersion": 12.55,
                "ExifTool:Warning": **"End of processing at large atom (LargeFileSupport not enabled)",**
                "File:FileName": "20230923_124112(AX700).MP4",
                "File:Directory": "2023-02-05",

I'm initializing EXIFtoolhelper like this:
from exiftool import ExifToolHelper, exceptions
e = ExifToolHelper()

Then I can get metadata with m = e.get_metadata(file).

How can I initialize EXIFtoolHelper with argument LargeFileSupport?

Thank you.

**Comment by sylikc** [comment]
Hi, the [ExifToolHelper.get_metadata()](https://sylikc.github.io/pyexiftool/reference/2-helper.html#exiftool.ExifToolHelper.get_metadata) has a `params` to pass any additional args (like enabling LFS)

From ExifTool forums [How to enable LargeFileSupport?](https://exiftool.org/forum/index.php?topic=9845.0), you have to specify `-api largefilesupport=1`

So your call should be

```python
e = ExifToolHelper()
e.get_metadata(file, params=['-api', 'largefilesupport=1'])
```

You can also initialize the [common_args](https://sylikc.github.io/pyexiftool/reference/1-exiftool.html#exiftool.ExifTool.__init__) to include that, if you so choose... and that will use those params every time

```python
e = ExifToolHelper(common_args=['-G', '-n', '-api', 'largefilesupport=1']
e.get_metadata(file)
```

**Comment by llitkr** [comment]
> Hi, the [ExifToolHelper.get_metadata()](https://sylikc.github.io/pyexiftool/reference/2-helper.html#exiftool.ExifToolHelper.get_metadata) has a `params` to pass any additional args (like enabling LFS)
> 
> From ExifTool forums [How to enable LargeFileSupport?](https://exiftool.org/forum/index.php?topic=9845.0), you have to specify `-api largefilesupport=1`
> 
> So your call should be
> 
> ```python
> e = ExifToolHelper()
> e.get_metadata(file, params=['-api', 'largefilesupport=1'])
> ```
> 
> You can also initialize the [common_args](https://sylikc.github.io/pyexiftool/reference/1-exiftool.html#exiftool.ExifTool.__init__) to include that, if you so choose... and that will use those params every time
> 
> ```python
> e = ExifToolHelper(common_args=['-G', '-n', '-api', 'largefilesupport=1']
> e.get_metadata(file)
> ```

Thank you sylikc. It solved perfect.
I thought I should pass the paremeter with one string but now I realized I need to pass it with array.

**Comment by sylikc** [comment]
Cool. Everything regarding the parameters and using ExifTool class is going to be lists. Any time on the command line there's a space, it's another parameter.

Read the docs for more descriptions and the FAQ for other common use cases

**Comment by sylikc** [comment]
Hi, I just updated the FAQ to help in the future for any type of arguments setting: https://sylikc.github.io/pyexiftool/faq.html#shlex-split
