### ISSUE TITLE
get_metadata returns numerical values instead of descriptive ones

### ISSUE THREAD

**Issue by paolobenve** [sylikc/pyexiftool#93]
I'd expect get_metadata return something like executing "exiftool file"

"exiftool file" returns many values as Orientation, Sensitivity Type, Metering Mode, etc. with descriptive values: "normal", "Standard Output Sensitivity", etc.

however, get_metadata without any parameter returns numeric values for all those tags for which "exiftool file" returns a descriptive one.

**Comment by paolobenve** [comment]
The explication:

https://sylikc.github.io/pyexiftool/faq.html#pyexiftool-output-is-different-from-the-exiftool-command-line

closing,

**Comment by sylikc** [comment]
glad the FAQ helped!
